baseURL: "https://charging.pluq.eu"
languageCode: "en-us"
title: "Pluq"
pygmentsstyle: "monokai"
metaDataFormat: yaml

# Theme settings
# theme: novela
module:
  imports:
    - path: "github.com/forestryio/hugo-theme-novela"
paginate: 10
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
google: "https://play.google.com"
apple: "https://www.apple.com/app-store/"
